version: '3.8'
services:
  web:
    image: nginx:latest
    deploy:
      replicas: 8
      placement:
        constraints: [node.role==worker]
    ports:
      - "80:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 4
      placement:
        constraints: [node.role==worker]
  redis:
    image: redis:latest
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:

  db_data:
