version: "3.8"
services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
  db:
    image: postgres:stable
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database
    deploy:
      replicas: 4
      placement:
        constraints: [node.role==worker]
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

